# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='create_date',
            new_name='start_date',
        ),
    ]
