# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.ManyToManyField(related_name='class_student', to='home.Student'),
        ),
    ]
