# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171111_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Comments',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
