# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_grade',
            new_name='Student_Class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_email',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_curr_grade',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_prev_grade',
            field=models.CharField(default='F', max_length=10),
        ),
    ]
