# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171113_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='student',
        ),
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
