# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171201_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='student',
        ),
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.ManyToManyField(related_name='class_student', to='home.Student'),
        ),
    ]
