# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171201_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='attendance',
        ),
    ]
