# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_classname_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_Id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_email',
            field=models.EmailField(max_length=49, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Parents_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_curr_grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_name',
            field=models.CharField(max_length=49, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_prev_grade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
