# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171203_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(max_length=3)),
                ('attend_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='home.Student')),
            ],
        ),
    ]
