# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend',
            field=models.BooleanField(default=False),
        ),
    ]
