# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20171203_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_name',
            field=models.CharField(max_length=49, null=True),
        ),
    ]
