# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171204_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(default='attendance remarks', max_length=250),
        ),
    ]
